/*******************************************************************************
   Include file Noa_Nofusion_dsmpbap.c:

   Declaration of asynchronous tasks generated by DSMPB Trigger Event Block

   Wed Mar  9 12:18:59 2022

   (c) Copyright 2020, dSPACE GmbH. All rights reserved.

 ******************************************************************************/

#include "Noa_Nofusion_dsmpbap.h"
#include "Noa_Nofusion.h"
#include "Noa_Nofusion_private.h"

/* Declarations of trigger task access points            */
/* Access point for triggered task function of block Noa_Nofusion/UDP Receive (3)\Data Received/Trigger Event Port S-Fcn    */
void dsmpb_event_task_Noa_Nofusion_TriggerEventPortSFcn_TID3_BT1(void)
{
  {
    /* S-Function (dsmpb_triggereventport): '<S24>/Trigger Event Port S-Fcn' */
    Noa_Nofusion_Subsystem3();

    /* End of Outputs for S-Function (dsmpb_triggereventport): '<S24>/Trigger Event Port S-Fcn' */
  }
}

/* Access point for triggered task function of block Noa_Nofusion/UDP Receive 2\Data Received/Trigger Event Port S-Fcn    */
void dsmpb_event_task_Noa_Nofusion_TriggerEventPortSFcn_o_TID4_BT2(void)
{
  {
    /* S-Function (dsmpb_triggereventport): '<S25>/Trigger Event Port S-Fcn' */
    Noa_Nofusion_UDP_Received();

    /* End of Outputs for S-Function (dsmpb_triggereventport): '<S25>/Trigger Event Port S-Fcn' */
  }
}
